version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5000
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - '5000:5000'

  redis:
    image: redis